-- DATABASE DESIGN
CREATE DATABASE Lumon;
USE Lumon;

CREATE TABLE CUSTOMER
(
    CUST_ID CHAR(3) PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(15),
    PHONE_NUM CHAR(12),
    DEPARTMENT VARCHAR(30)
);


CREATE TABLE PRODUCT
(
    PRODUCT_ID CHAR(5) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    CATEGORY VARCHAR(30) NOT NULL,
    PRICE DECIMAL(4, 2) NOT NULL
);
           

CREATE TABLE ORDERS
(
    ORDER_ID CHAR(6) PRIMARY KEY,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL(7, 2),
    CUST_ID CHAR(3)
);

ALTER TABLE ORDERS
    ADD FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID);
           


CREATE TABLE ORDER_DETAIL
(
    ORDER_DETAIL_ID CHAR(1) PRIMARY KEY,
    ORDER_ID CHAR(6),
    PRODUCT_ID CHAR(5),
    QUANTITY INT,
    UNIT_PRICE DECIMAL(4,2)
);

ALTER TABLE ORDER_DETAIL
    ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

ALTER TABLE ORDER_DETAIL
    ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);




